const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.join(__dirname, '..');
const store = {};
const local = { console, Date, Math, localStorage: { getItem: k => store[k] || null, setItem: (k,v) => store[k] = String(v), removeItem: k => delete store[k] } };
local.window = local;
vm.createContext(local);
vm.runInContext(fs.readFileSync(path.join(root, 'assets/js/data.js'), 'utf8'), local);
const D = local.PNC_DB; D.load();
D.logIn('elena@example.com', 'member123');
assert(D.updatePet('pt-3', { petName: 'unauthorized' }).error);
const originalOwner = D.currentOwner().id;
D.adminLogin('owner@pawsandclaws.example', 'admin123');
const customer = D.createOwner({fullName:'Audit Customer',email:'audit@example.com'}).owner;
assert(customer && !customer.passwordHash);
assert.equal(D.currentOwner().id, originalOwner, 'CRM creation must not switch the member session');
assert(D.createOwner({fullName:'Duplicate',email:'audit@example.com'}).error);
assert(!D.sendMessage(originalOwner,'Care update','Your visit is confirmed.').error);
const message = D.db.messages.at(-1);
assert.equal(message.direction, 'out');
assert(!D.markMessageRead(message.id).error);
assert.equal(message.read,true);
D.db.messages.push({id:'foreign',ownerId:'ow-2',direction:'out',read:false});
assert(D.markMessageRead('foreign').error);
D.adminLogout();
const available = D.SERVICES.flatMap(s => D.slotsFor(D.db,s.id,D.addDays(3)).filter(x=>x.available).map(x=>({...x,serviceId:s.id})))[0];
const occupied = {id:'audit-bk',ownerId:originalOwner,petId:'pt-1',serviceId:available.serviceId,providerId:available.providerId,date:D.addDays(3),hour:available.hour,duration:1,status:'confirmed'};
D.db.bookings.push(occupied);
assert(!D.rescheduleBooking(occupied.id,occupied.date,occupied.hour).error, 'same appointment slot must ignore itself');
D.db.bookings.push({...occupied,id:'occupied',hour:occupied.hour+0.5});
assert(D.rescheduleBooking(occupied.id,occupied.date,occupied.hour+0.5).error, 'overlapping slot must be rejected');
D.adminLogin('rosa@pawsandclaws.example','rosa123');
const other = D.db.bookings.find(b=>b.providerId!=='Rosa');
assert(D.addBookingNote(other.id,'Not my appointment').error);
D.adminLogout();
D.db.payments = [{id:'mine',ownerId:originalOwner,primary:false},{id:'theirs',ownerId:'ow-2',primary:true}];
D.setPrimaryPayment('mine');
assert.equal(D.db.payments.find(p=>p.id==='theirs').primary,true);
assert(D.addPaymentMethod(originalOwner,'Visa','1234',13,2030).error);
D.adminLogin('owner@pawsandclaws.example', 'admin123');
const walkIn = D.createOwner({fullName: 'Walk In', phone: '01234'}).owner;
assert(walkIn && walkIn.email === '');
assert(D.createOwner({fullName: 'Other Walk In'}).owner, 'blank email is not a shared account');
assert(!D.updateOwner(walkIn.id, {phone: '56789', email: ''}).error);
const item = D.db.products[0], beforeStock = item.stock;
const sale = D.posCharge('', [{productId: item.id, qty: 2, amount: 0.01}], 'Cash', {requestId: 'local-sale-001', tendered: 100});
assert(!sale.error, sale.error);
assert.equal(sale.total, Math.round(item.price * 200) / 100);
assert.equal(item.stock, beforeStock - 2);
assert.equal(sale.order.items[0].label, item.name);
assert.equal(sale.order.change, 100 - sale.total);
assert.equal(D.fmtDate(sale.order.placedAt),D.fmtDate(sale.order.placedAt.slice(0,10)));
assert.equal(D.money(1234),'\u20a61234.00');
assert.equal(D.posCharge('', [{productId:item.id, qty:2}], 'Cash', {requestId:'local-sale-001'}).order.id, sale.order.id);
assert.equal(item.stock, beforeStock - 2, 'retry must not decrement stock twice');
const beforeRefundRevenue = D.stats().revenueRetail;
assert(!D.refundStoreSale(sale.order.id, 5, 'Cash', {requestId:'local-refund-001',reason:'Returned item'}).error);
assert(!D.refundStoreSale(sale.order.id, 5, 'Cash', {requestId:'local-refund-001',reason:'Returned item'}).error);
assert.equal(sale.order.refunded, 5);
assert.equal(D.stats().revenueRetail, beforeRefundRevenue - 5);
assert(D.refundStoreSale(sale.order.id, sale.total, 'Cash', {requestId:'local-refund-002',reason:'Too much'}).error);
assert.equal(item.stock, beforeStock - 2, 'refund does not restock without an inventory check');
assert(D.posCharge('', [{productId:item.id,qty:beforeStock},{productId:item.id,qty:1}], 'Cash', {requestId:'local-sale-002'}).error);
assert(D.posCharge('', [{label:'Care',qty:1,amount:10}], 'Cash', {requestId:'local-sale-003',tendered:9}).error);
assert(D.posCharge('', [{label:'Care',qty:0.5,amount:10}], 'Cash', {requestId:'local-sale-004'}).error);
const walkPet = D.addPet(walkIn.id, {petName:'Visitor',species:'Dog'}).pet;
const openService = D.SERVICES.find(s=>!s.requiresVaccine && s.duration<24);
const storeSlot = D.slotsFor(D.db,openService.id,D.addDays(5)).find(s=>s.available);
const visit = D.staffBooking({ownerId:walkIn.id,petId:walkPet.id,serviceId:openService.id,date:D.addDays(5),...storeSlot}).booking;
assert(!D.addVaccine(walkPet.id, 'Rabies', D.todayISO(), 'test-record').error);
assert.equal(walkPet.vaccines[0].status,'pending');
assert(visit); assert.equal(visit.paid,0); assert.equal(visit.total,openService.price);
assert(!D.recordBookingPayment(visit.id, 1, 'Cash', {requestId:'local-payment-01'}).error);
assert(!D.recordBookingPayment(visit.id, 1, 'Cash', {requestId:'local-payment-01'}).error);
assert.equal(visit.paid,1); assert(D.recordBookingPayment(visit.id,visit.total,'Cash',{requestId:'local-payment-02'}).error);
D.adminLogout();
assert(D.posCharge('', [{productId:item.id,qty:1}], 'Cash', {requestId:'local-sale-005'}).error);
assert(D.staffBooking({ownerId:walkIn.id}).error);
console.log('Local member/admin workflow tests passed.');

// Execute the real Convex handlers with a deterministic in-memory database.
// No deployed data or network calls are used.
let who = null;
const tables = {};
let serial = 0;
const db = {
 query(table) {
   let rows = tables[table] ||= [];
   const query = { withIndex(name, fn) { const q = {eq(k,v){rows=rows.filter(r=>r[k]===v);return q;}};fn(q);return query; },
     filter(fn) { const expr = {field:k=>k,eq:(k,v)=>r=>r[k]===v};rows=rows.filter(fn(expr));return query; },
     async collect(){return rows.map(r=>({...r}));}, async first(){return rows[0] || null;} };
   return query;
 },
 async insert(table,row){const id='doc-'+(++serial);(tables[table] ||= []).push({...row,_id:id});return id;},
 async patch(id,patch){assert(id,'patch requires document ID');for(const rows of Object.values(tables)){const row=rows.find(r=>r._id===id);if(row){Object.assign(row,patch);return;}}throw Error('Missing doc');},
 async delete(id){for(const key of Object.keys(tables)) tables[key]=tables[key].filter(r=>r._id!==id);}
};
const backend = {console,crypto,process:{env:{}},mutation:x=>x,query:x=>x,v:{string:()=>({}),any:()=>({})}};
vm.createContext(backend);
let source=fs.readFileSync(path.join(root,'convex/domain.js'),'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export const (\w+) =/g,'globalThis.$1 =');
vm.runInContext(source,backend);
const ctx={db,auth:{getUserIdentity:async()=>who}};
const run=(op,payload={})=>backend.mutate.handler(ctx,{op,payload});
(async()=>{
 await db.insert('listings',{id:'pet-public',status:'available'});
 const anonymous=await backend.bootstrap.handler(ctx);
 assert.equal(anonymous.listings.length,1);
 assert.equal(anonymous.owners.length,0);
 who={subject:'user-new',email:'new@example.com',emailVerified:true,name:'New Member'};
 await run('ensureOwner');
 assert.equal(tables.owners.length,1);
 assert.equal(tables.owners[0].clerkId,'user-new');
 const owner=tables.owners[0];
 await db.patch(owner._id,{notes:'Private staff notes'});
 // Unverified email claims and a different subject must never inherit records.
 who={subject:'attacker',email:owner.email,emailVerified:false};
 assert.equal((await backend.bootstrap.handler(ctx)).owners.length,0);
 await assert.rejects(run('ensureOwner'),/Verify/);
 who={subject:'attacker',email:owner.email,emailVerified:true};
 assert.equal((await backend.bootstrap.handler(ctx)).owners.length,0);
 await assert.rejects(run('ensureOwner'),/another account/);
 assert.equal(tables.owners[0].clerkId,'user-new');
 who={subject:'user-new',email:owner.email,emailVerified:true};
 assert.equal((await backend.bootstrap.handler(ctx)).owners[0].notes,undefined);
 await assert.rejects(run('updateOwner',{patch:{notes:'User overwrite'}}),/staff/);
 await assert.rejects(run('updateOwner',{ownerId:owner.id,patch:{fullName:''}}),/short/);
 await assert.rejects(run('updateOwner',{ownerId:owner.id,patch:{plan:'senior'}}),/billing/);
 await db.insert('messages',{id:'private',ownerId:'another',direction:'out',read:false});
 await assert.rejects(run('markMessageRead',{messageId:'private'}),/authorized/);
 await assert.rejects(run('createOwner',{input:{fullName:'Test',email:'t@example.com'}}),/authorized/);
 await db.insert('bookings',{id:'b1',ownerId:owner.id,providerId:'Dana',internalNotes:[{note:'staff only'}],status:'confirmed'});
 const member=await backend.bootstrap.handler(ctx);
 assert.equal(member.bookings[0].internalNotes,undefined);
 await db.insert('admins',{id:'staff',clerkId:'staff-user',email:'staff@example.com',role:'super',name:'Admin'});
 who={subject:'attacker',email:'staff@example.com',emailVerified:true};
 assert.equal((await backend.bootstrap.handler(ctx)).admins.length,0);
 await assert.rejects(run('updateCMS',{patch:{banner:'Unauthorized'}}),/authorized/);
 await db.insert('admins',{id:'unlinked',email:'unlinked@example.com',role:'desk',name:'Desk'});
 who={subject:'unverified',email:'unlinked@example.com',emailVerified:false};
 await assert.rejects(run('createOwner',{input:{fullName:'Attacker',email:'attacker@example.com'}}),/authorized/);
 who={subject:'verified-staff',email:'unlinked@example.com',emailVerified:true};
 await run('ensureOwner');
 assert.equal(tables.admins.find(a=>a.id==='unlinked').clerkId,'verified-staff');
 who={subject:'staff-user',email:'staff@example.com'};
 await run('createOwner',{input:{fullName:'New Customer',email:'customer@example.com'}});
 await assert.rejects(run('createOwner',{input:{fullName:'Duplicate',email:'customer@example.com'}}),/already/);
 backend.process.env.PNC_PAYMENTS_ENABLED='true';
 await db.insert('products',{id:'product-audit',name:'Test product',price:5,stock:4,lowAt:1});
 await db.insert('pets',{id:'pet-audit',ownerId:owner.id,petName:'Test pet',species:'Dog',vaccines:[]});
 await db.insert('services',{id:'svc-deposit',name:'Deposit service',price:100,duration:1,deposit:true,requiresVaccine:false,staff:['Dana']});
 who={subject:'user-new',email:'new@example.com'};
 await assert.rejects(run('placeOrder',{items:[{id:'product-audit',qty:1}]}),/disabled|not connected/i);
 await assert.rejects(run('createBooking',{petId:'pet-audit',serviceId:'svc-deposit',providerId:'Dana',date:'2026-10-20',hour:9}),/disabled|not connected/i);
 assert.equal(tables.products.find(r=>r.id==='product-audit').stock,4,'unpaid checkout must not reserve inventory');
 assert.equal((tables.bookings||[]).some(r=>r.serviceId==='svc-deposit'),false,'unpaid deposit booking must not reserve a slot');
 who={subject:'staff-user',email:'staff@example.com'};
 await db.insert('cms',{id:'site',hours:[]});
 await assert.rejects(run('updateCMS',{patch:{hours:[{day:'Monday',open:'9:00 AM',close:'7:00 PM'}]}}),/complete/);
 const realHours=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(day=>({day,open:'Closed',close:'Closed'}));
 realHours[0]={day:'Monday',open:'9:00 AM',close:'5:00 PM'};
 await run('updateCMS',{patch:{hours:realHours}});
 assert.equal(tables.cms[0].hours[0].close,'5:00 PM');
 const service=await db.insert('services',{id:'svc-audit',name:'Audit service',price:20,duration:1});
 await run('updateService',{serviceId:'svc-audit',patch:{name:'Edited service',price:25,duration:1.5}});
 assert.equal((await run('updateService',{serviceId:'svc-audit',patch:{price:25}})).serviceId,'svc-audit');
 assert.equal(tables.services.find(r=>r.id==='svc-audit').price,25);
 await assert.rejects(run('updateService',{serviceId:'svc-audit',patch:{duration:13}}),/duration/);
 const contact=await db.insert('contactMessages',{id:'contact-audit',status:'new'});
 await run('setContactStatus',{contactId:'contact-audit',status:'resolved'});
 assert.equal(tables.contactMessages.find(r=>r.id==='contact-audit').status,'resolved');
 await run('sendMessage',{ownerId:owner.id,subject:'Update',body:'Your appointment is ready.'});
 const sent=tables.messages.at(-1);
 assert.equal(sent.channel,'portal');
 who={subject:'user-new',email:'new@example.com'};
 await run('markMessageRead',{messageId:sent.id});
 assert.equal(sent.read,true);
 await db.insert('admins',{id:'provider',clerkId:'provider-user',email:'provider@example.com',role:'provider',providerId:'Rosa',name:'Provider'});
 who={subject:'provider-user',email:'provider@example.com'};
 await assert.rejects(run('addBookingNote',{bookingId:'b1',note:'Forbidden'}),/authorized/);
 await assert.rejects(run('sendMessage',{ownerId:owner.id,subject:'Hello',body:'Forbidden'}),/authorized/);
 who={subject:'staff-user',email:'staff@example.com'};
 await db.insert('products',{id:'private-product',price:10,stock:10,lowAt:2,cost:4});
 const stockResult=await run('adjustStock',{productId:'private-product',delta:1});
 assert.equal(stockResult.productId,'private-product');
 await db.insert('staffLeave',{id:'private-leave',providerId:'Rosa',date:'2026-11-01',reason:'Sensitive reason'});
 await db.insert('bookings',{id:'occupied-private',providerId:'Dana',date:'2099-10-20',hour:9,duration:1,ownerId:'another',status:'confirmed'});
 await assert.rejects(run('addLeave',{providerId:'Dana',date:'2099-10-20'}),/appointments/);
 await assert.rejects(run('addLeave',{providerId:'Dana',date:'2099-02-31'}),/Invalid/);
 await db.insert('orders',{id:'closed-order',stage:'done',status:'delivered',ownerId:owner.id});
 await assert.rejects(run('setOrderStage',{orderId:'closed-order',stage:'shipped'}),/Closed/);
 await db.insert('services',{id:'svc-open',name:'Open service',price:20,duration:1,staff:['Dana'],deposit:false,requiresVaccine:false});
 who={subject:'user-new',email:owner.email,emailVerified:true};
 await assert.rejects(run('createBooking',{petId:'pet-audit',serviceId:'svc-open',providerId:'Dana',date:'2099-10-20',hour:9}),/available/);
 const newBooking=await run('createBooking',{petId:'pet-audit',serviceId:'svc-open',providerId:'Dana',date:'2099-10-20',hour:10});
 assert.equal(tables.bookings.find(x=>x.id===newBooking.bookingId).total,20,'live accounts do not receive unconfigured demo discounts');
 await run('rescheduleBooking',{bookingId:newBooking.bookingId,date:'2099-10-20',hour:10});
 await assert.rejects(run('createBooking',{petId:'pet-audit',serviceId:'svc-open',providerId:'Dana',date:'2099-10-20',hour:10}),/available/);
 who={subject:'staff-user',email:'staff@example.com'};
 const walkInResult=await run('createOwner',{input:{fullName:'Counter Customer'}});
 await run('createOwner',{input:{fullName:'Second Counter Customer'}});
 await run('updateOwner',{ownerId:walkInResult.ownerId,patch:{email:'',phone:'123'}});
 await run('addVaccine',{petId:'pet-audit',name:'Rabies',date:'2026-10-01',lot:'test-record'});
 assert.equal(tables.pets.find(p=>p.id==='pet-audit').vaccines.at(-1).status,'pending');
 const productBefore=tables.products.find(x=>x.id==='product-audit').stock;
 const counterSale=await run('posCharge',{ownerId:'',lines:[{productId:'product-audit',qty:2,amount:0.01}],method:'Cash',options:{requestId:'server-sale-001',tendered:20}});
 assert.equal(counterSale.total,10);
 assert.equal(tables.products.find(x=>x.id==='product-audit').stock,productBefore-2);
 const refundResult=await run('refundStoreSale',{orderId:counterSale.orderId,amount:3,method:'Cash',options:{requestId:'server-refund-001',reason:'Returned item'}});
 assert.equal(refundResult.orderId,counterSale.orderId);
 await run('refundStoreSale',{orderId:counterSale.orderId,amount:3,method:'Cash',options:{requestId:'server-refund-001',reason:'Returned item'}});
 assert.equal(tables.orders.find(x=>x.id===counterSale.orderId).refunded,3);
 await assert.rejects(run('refundStoreSale',{orderId:counterSale.orderId,amount:8,method:'Cash',options:{requestId:'server-refund-002',reason:'Too much'}}),/exceed/);
 assert.equal(tables.products.find(x=>x.id==='product-audit').stock,productBefore-2);
 assert.equal(tables.orders.find(x=>x.id===counterSale.orderId).change,10);
 await run('posCharge',{lines:[{productId:'product-audit',qty:2}],method:'Cash',options:{requestId:'server-sale-001'}});
 assert.equal(tables.products.find(x=>x.id==='product-audit').stock,productBefore-2);
 await assert.rejects(run('posCharge',{lines:[{productId:'product-audit',qty:2},{productId:'product-audit',qty:1}],method:'Cash',options:{requestId:'server-sale-002'}}),/stock/);
 await assert.rejects(run('posCharge',{lines:[{productId:'product-audit',qty:-1}],method:'Cash',options:{requestId:'server-sale-003'}}),/Quantity/);
 await assert.rejects(run('posCharge',{lines:[{label:'Service',amount:10}],method:'Cash',options:{requestId:'server-sale-004',tendered:9}}),/cover/);
 assert.equal(tables.products.find(x=>x.id==='product-audit').stock,productBefore-2, 'failed sale leaves stock intact');
 const staffVisit=await run('staffBooking',{ownerId:owner.id,petId:'pet-audit',serviceId:'svc-deposit',providerId:'Dana',date:'2099-10-20',hour:12});
 const visitRow=tables.bookings.find(x=>x.id===staffVisit.bookingId);
 assert.equal(visitRow.createdBy,'staff'); assert.equal(visitRow.paid,0); assert.equal(visitRow.total,100);
 await run('recordBookingPayment',{bookingId:visitRow.id,amount:30,method:'Bank transfer',options:{requestId:'server-pay-001',reference:'BANK-123'}});
 await run('recordBookingPayment',{bookingId:visitRow.id,amount:30,method:'Bank transfer',options:{requestId:'server-pay-001'}});
 assert.equal(visitRow.paid,30); assert.equal(visitRow.storePayments.length,1);
 await assert.rejects(run('recordBookingPayment',{bookingId:visitRow.id,amount:71,method:'Cash',options:{requestId:'server-pay-002'}}),/balance/);
 await run('recordBookingPayment',{bookingId:visitRow.id,amount:70,method:'Cash',options:{requestId:'server-pay-003'}});
 assert.equal(visitRow.paid,100); assert.equal(visitRow.paymentStatus,'paid');
 who={subject:'user-new',email:owner.email,emailVerified:true};
 await assert.rejects(run('staffBooking',{ownerId:owner.id}),/authorized/);
 await assert.rejects(run('posCharge',{lines:[{productId:'product-audit',qty:1}],method:'Cash',options:{requestId:'unauthorized-sale'}}),/authorized/);
 await assert.rejects(run('recordBookingPayment',{bookingId:visitRow.id,amount:1,method:'Cash',options:{requestId:'unauthorized-payment'}}),/authorized/);
 await assert.rejects(run('refundStoreSale',{orderId:counterSale.orderId,amount:1,method:'Cash',options:{requestId:'unauthorized-refund',reason:'No access'}}),/authorized/);
 who=null;
 const publicSnapshot=await backend.bootstrap.handler(ctx);
 assert.equal(publicSnapshot.products.find(p=>p.id==='private-product').cost,undefined);
 assert.equal(publicSnapshot.staffLeave[0].reason,undefined);
 assert.equal(publicSnapshot.staffLeave[0].id,undefined);
 assert.equal(publicSnapshot.occupiedSlots[0].ownerId,undefined);
 assert.equal(publicSnapshot.occupiedSlots[0].id,undefined);
 await assert.rejects(run('submitInquiry',{listingId:'pet-public'}),/name/);
 await run('submitInquiry',{listingId:'pet-public',name:'Guest Visitor',email:'guest@example.com',message:'Can I meet this pet?'});
 assert.equal(tables.inquiries.at(-1).email,'guest@example.com');
 assert.equal(tables.inquiries.at(-1).name,'Guest Visitor');
 assert.equal((await backend.bootstrap.handler(ctx)).inquiries.length,0);
 for(let i=0;i<4;i++) await run('submitContact',{name:'Guest Visitor',email:'guest@example.com',body:'A test message for the team.'});
 await assert.rejects(run('submitContact',{name:'Guest Visitor',email:'guest@example.com',body:'A test message for the team.'}),/Too many/);
 assert(!/<img/.test(D.icon('<img src=x onerror=alert(1)>')));
 assert.equal(D.icon('&#128062;'),'&#128062;');
 D.db.products[0].price=123;
 assert.equal(D.PRODUCT_BY_ID[D.db.products[0].id].price,123);
 console.log('Convex authorization and workflow tests passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
